Controllers/Party/PartyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PartyProductAPI.Models;
using PartyProductAPI.Repository;
using System.Threading.Tasks;

namespace PartyProductAPI.Controllers.Party
{
    [Route("[controller]/[action]")]
    //[ApiController]
    //[Authorize]
    public class PartyController : Controller
    {
        [ViewData]
        public string Title { get; set; }

        private readonly IPartyRepository _partyRepository;

        public PartyController(IPartyRepository partyRepository)
        {
            _partyRepository = partyRepository;
        }


        // ---------------------------------------------------------------
        [Route("~/")]
        public async Task<IActionResult> GetAllParty()
        {
            var result = await _partyRepository.GetAllParty();
            //return Ok(result);
            Title = "Party | Invoice App";
            return View("GetAllParty", result);
        }


        // ---------------------------------------------------------------
        [HttpGet("{id:int}")]
        public async Task<IActionResult> GetPartyById([FromRoute] int id)
        {
            var result = await _partyRepository.GetPartyById(id);
            if (result == null)
            {
                return NotFound();
            }
            return Ok(result);
        }


        // ---------------------------------------------------------------
        [HttpGet]
        public async Task<ViewResult> AddNewParty()
        {
            ViewBag.Success = false;
            return View("AddNewParty");
        }

        [HttpPost]
        public async Task<IActionResult> AddNewParty([FromForm] PartyModel party)
        {
            if (ModelState.IsValid)
            {
                await _partyRepository.AddNewParty(party);
                ViewBag.Success = true;
                return View("AddNewParty");
            }
            ViewBag.Success = false;
            return View("AddNewParty");
        }


        // ---------------------------------------------------------------
        [HttpGet("{id:int}")]
        public async Task<ViewResult> UpdateParty(int id)
        {
            var findParty = await _partyRepository.GetPartyById(id);
            ViewBag.Party = findParty;
            ViewBag.Success = false;
            return View("UpdateParty");
        }

        [HttpPost("{id:int}")]
        public async Task<IActionResult> UpdateParty([FromRoute] int id, [FromForm] PartyModel party)
        {
            if (ModelState.IsValid)
            {
                await _partyRepository.UpdateParty(id, party);
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.Success = false;
            }

            ViewBag.Party = party;
            return View("UpdateParty");
        }


        // ---------------------------------------------------------------
        [HttpGet]
        //[Route("{id:int}")]
        public async Task<IActionResult> DeleteParty(int id)
        {
            await _partyRepository.DeleteParty(id);
            return View("GetAllParty");
            //return RedirectToAction(actionName: "GetAllParty", controllerName: "Party");
        }
    }
}

Controllers/PartyProduct/PartyProductController.cs
using Microsoft.AspNetCore.Mvc;
using PartyProductAPI.Models;
using PartyProductAPI.Repository;
using System.Threading.Tasks;

namespace PartyProductAPI.Controllers.PartyProduct
{
    [Route("[controller]/[action]")]
    //[ApiController]
    //[Authorize]
    public class PartyProductController : Controller
    {
        private readonly IPartyProductRepository _partyProductRepository;
        private readonly IPartyRepository _partyRepository;
        private readonly IProductRepository _productRepository;

        public PartyProductController(IPartyProductRepository partyProductRepository, IPartyRepository partyRepository, IProductRepository productRepository)
        {
            _partyProductRepository = partyProductRepository;
            _partyRepository = partyRepository;
            _productRepository = productRepository;
        }

        [ViewData]
        public string Title { get; set; }


        // -------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> GetAllAssign()
        {
            var result = await _partyProductRepository.GetAllAssignAsync();

            //if (result.Count > 0)
            //{
            //    return Ok(result);
            //}
            //return NoContent();

            Title = "Assign | Invoice App";
            return View("GetAllAssign", result);
        }

        [HttpGet("{id:int}")]
        public async Task<IActionResult> GetAssignById(int id)
        {
            var result = await _partyProductRepository.GetAssignById(id);

            if (result != null)
            {
                return Ok(result);
            }

            return NotFound();
        }


        // -------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> AddNewAssign()
        {
            ViewBag.Success = false;
            return View("AddNewAssign");
        }

        [HttpPost]
        public async Task<IActionResult> AddNewAssign([FromForm] PartyProductModel assign)
        {
            if (ModelState.IsValid)
            {
                await _partyProductRepository.AddNewAssignAsync(assign);
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.Success = false;
            }

            return RedirectToAction("AddNewAssign");
        }


        // -------------------------------------------------------------------------------
        [HttpGet("{id:int}")]
        public async Task<IActionResult> UpdateAssign([FromRoute] int id)
        {
            var tempParty = await _partyProductRepository.GetAssignById(id);
            ViewBag.SelectedParty = tempParty.PartyId;
            ViewBag.SelectedProduct = tempParty.ProductId;
            ViewBag.Success = false;
            return View();
        }

        [HttpPost("{id:int}")]
        public async Task<IActionResult> UpdateAssign([FromRoute] int id, [FromForm] PartyProductModel assign)
        {
            if (ModelState.IsValid)
            {
                await _partyProductRepository.UpdateAssignAsync(id, assign);
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.Success = false;
            }

            var tempParty = await _partyProductRepository.GetAssignById(id);
            ViewBag.SelectedParty = tempParty.PartyId;
            ViewBag.SelectedProduct = tempParty.ProductId;
            return View();
        }



        // -------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> DeleteAssign(int id)
        {
            await _partyProductRepository.DeleteAssignAsync(id);
            return View("GetAllAssign");
        }


        // -------------------------------------------------------------------------------
        [HttpPost("{id}")]
        public async Task<IActionResult> BindProduct(string id)
        {
            var resultProduct = await _partyProductRepository.BindProduct(id);
            return Json(resultProduct);
        }
    }
}

Controllers/Product/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PartyProductAPI.Models;
using PartyProductAPI.Repository;
using System.Threading.Tasks;

namespace PartyProductAPI.Controllers.Product
{
    [Route("[controller]/[action]")]
    //[ApiController]
    //[Authorize]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;

        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        [ViewData]
        public string Title { get; set; }


        // ---------------------------------------------------------------
        //[HttpGet]
        public async Task<IActionResult> GetAllProduct()
        {
            var result = await _productRepository.GetAllProduct();
            //return Ok(result);
            Title = "Product | Invoice App";
            return View("GetAllProduct", result);
        }

        //[HttpGet("{id:int}")]
        public IActionResult GetProductById([FromRoute] int id)
        {
            var result = _productRepository.GetProductById(id).Result;
            if (result == null)
            {
                return NotFound();
            }
            return Ok(result);
        }


        // ---------------------------------------------------------------
        public async Task<ViewResult> AddNewProduct()
        {
            ViewBag.Success = false;
            return View("AddNewProduct");
        }

        [HttpPost]
        public async Task<IActionResult> AddNewProduct([FromForm] ProductModel product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.AddNewProduct(product);
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.Success = false;
            }
            return View("AddNewProduct");
        }


        // ---------------------------------------------------------------
        [HttpGet("{id:int}")]
        public async Task<ViewResult> UpdateProduct(int id)
        {
            var findProduct = await _productRepository.GetProductById(id);
            ViewBag.Product = findProduct;
            ViewBag.Success = false;
            return View("UpdateProduct");
        }

        [HttpPost("{id:int}")]
        public async Task<IActionResult> UpdateProduct([FromRoute] int id, [FromForm] ProductModel product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.UpdateProduct(id, product);
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.Success = false;
            }

            ViewBag.Product = product;
            return View("UpdateProduct");
        }


        // ---------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            await _productRepository.DeleteProduct(id);
            return View("GetAllProduct");
        }
    }
}

Controllers/ProductRate/ProductRateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PartyProductAPI.Models;
using PartyProductAPI.Repository;
using System.Threading.Tasks;

namespace PartyProductAPI.Controllers.ProductRate
{
    [Route("[controller]/[action]")]
    //[ApiController]
    //[Authorize]
    public class ProductRateController : Controller
    {
        private readonly IProductRateRepository _productRateRepository;

        public ProductRateController(IProductRateRepository productRateRepository)
        {
            _productRateRepository = productRateRepository;
        }

        [ViewData]
        public string Title { get; set; }


        // -------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> GetAllProductRate()
        {
            var result = await _productRateRepository.GetAllProductRateAsync();
            //if (result == null)
            //{
            //    return NoContent();
            //}
            //return Ok(result);

            Title = "Product Rate | Invoice App";
            return View("GetAllProductRate", result);
        }

        [HttpGet("{id:int}")]
        public async Task<IActionResult> GetProductRateById([FromRoute] int id)
        {
            var result = await _productRateRepository.GetProductByIdAsync(id);
            if (result == null)
            {
                return NotFound();
            }
            return Ok(result);
        }


        // -------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> AddNewProductRate()
        {
            ViewBag.Success = false;
            return View("AddNewProductRate");
        }

        [HttpPost]
        public async Task<IActionResult> AddNewProductRate([FromForm] ProductRateModel productRate)
        {
            if (ModelState.IsValid)
            {
                await _productRateRepository.AddNewProductRateAsync(productRate);
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.Success = false;
            }
            return RedirectToAction("AddNewProductRate");
        }


        // -------------------------------------------------------------------------------
        [HttpGet("{id:int}")]
        public async Task<IActionResult> UpdateProductRate([FromRoute] int id)
        {
            var findRate = await _productRateRepository.GetProductByIdAsync(id);
            ViewBag.Rate = findRate;
            return View("UpdateProductRate");
        }

        [HttpPost("{id:int}")]
        public async Task<IActionResult> UpdateProductRate([FromRoute] int id, [FromForm] ProductRateModel productRateate)
        {
            var result = await _productRateRepository.UpdateNewRateAsync(id, productRateate);
            var findRate = await _productRateRepository.GetProductByIdAsync(id);
            ViewBag.Rate = findRate;
            return View();
        }


        // -------------------------------------------------------------------------------
        [HttpGet("{id:int}")]
        public async Task<IActionResult> DeleteProductRate([FromRoute] int id)
        {
            await _productRateRepository.DeleteRateAsync(id);
            return View("GetAllProductRate");
        }


        // -------------------------------------------------------------------------------
        [HttpPost("{id}")]
        public async Task<IActionResult> BindRate(string id)
        {
            var rateFind = await _productRateRepository.BindRate(id);
            return Json(rateFind);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
</head>
<body>

    <div>
        <partial name="_header" />
        <div>
            @RenderBody()
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~lib/jquery-validate/jquery.validate.js"></script>
        <script src="~lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~lib/jquery-validate/jquery.validate.min.js"></script>
        @*<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>*@
    </environment>

    @RenderSection("scripts", false)
</body>
</html>

Views/Shared/_footer.cshtml
<div class="mt-5">
    <footer class="text-center text-lg-start bg-light text-muted bg-dark">
        <section class="pt-2">
            <div class="container text-center text-md-start mt-5">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">Company name</h6>
                        <p>
                            Here you can use rows and columns to organize your footer content. Lorem ipsum
                            dolor sit amet, consectetur adipisicing elit.
                        </p>
                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            Products
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Angular</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">React</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Vue</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Laravel</a>
                        </p>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Pricing</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Settings</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Orders</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Help</a>
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                        <p>New York, NY 10012, US</p>
                        <custom-email-tag-helpers email="shivraj@weybee.in"></custom-email-tag-helpers>
                        <p>+ 01 234 567 89</p>
                    </div>
                </div>
            </div>
        </section>
    </footer>
</div>

Views/Shared/_header.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration _configuration

@{
    var appName = _configuration["AppName"];
}

<div class="bg-dark">
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light container">
        <div class="container-fluid px-5">
            <a class="navbar-brand" asp-controller="Party" asp-action="GetAllParty">@appName</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a asp-controller="Party" asp-action="GetAllParty" class="nav-link btn @(Context.Request.RouteValues["Controller"] as string == "Party" ? "text-white" : "")">Party</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Product" asp-action="GetAllProduct" class="nav-link btn @(Context.Request.RouteValues["Controller"] as string == "Product" ? "text-white" : "")">Product</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="PartyProduct" asp-action="GetAllAssign" class="nav-link btn @(Context.Request.RouteValues["Controller"] as string == "PartyProduct" ? "text-white" : "")">Assign Party</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="ProductRate" asp-action="GetAllProductRate" class="nav-link btn @(Context.Request.RouteValues["Controller"] as string == "ProductRate" ? "text-white" : "")">Product Rate</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Invoice" asp-action="GetAllInvoice" class="nav-link btn @(Context.Request.RouteValues["Controller"] as string == "Invoice" ? "text-white" : "")">Invoice</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>